import { chromium } from 'playwright';
const shots = new URL('../shots/', import.meta.url).pathname;
const browser = await chromium.launch({ headless: true, args: ['--ignore-gpu-blocklist', '--use-angle=metal', '--enable-gpu'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const logs = [];
page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) logs.push(m.text()); });
page.on('pageerror', (e) => logs.push(e.message));
await page.goto('http://127.0.0.1:8765/?autopilot=1&quality=0');
await page.waitForFunction(() => window.__game && window.__game.frames > 10);
await page.mouse.click(640, 400);
await page.evaluate(() => window.__game.setDay(0.93));
await page.waitForTimeout(2500);
const s = await page.evaluate(() => window.__game.sun);
const m = s.moon, az = Math.atan2(m[0], m[2]) * 180 / Math.PI, el = Math.asin(m[1]) * 180 / Math.PI;
await page.evaluate(([a, e]) => window.__game.look(a, e - 8), [az, el]);
await page.waitForTimeout(600);
await page.screenshot({ path: shots + 's1-moon.png' });
await page.evaluate(() => { window.__game.setDay(0.02); });
await page.waitForTimeout(1500);
const s2 = await page.evaluate(() => window.__game.sun);
await page.evaluate((a) => window.__game.look(a, 6), s2.az);
await page.waitForTimeout(600);
await page.screenshot({ path: shots + 's2-dawn-sun.png' });
console.log('logs', logs.length, logs.slice(0, 5));
await browser.close();
